"""empty message

Revision ID: 00a318354350
Revises: c9398d8d57f2
Create Date: 2019-04-16 00:57:31.588562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00a318354350'
down_revision = 'c9398d8d57f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('contact_no', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('first_name', sa.String(length=50), nullable=False))
    op.add_column('user', sa.Column('last_name', sa.String(length=50), nullable=False))
    op.add_column('user', sa.Column('public_id', sa.String(length=100), nullable=True))
    op.drop_constraint('user_public_name_key', 'user', type_='unique')
    op.create_unique_constraint(None, 'user', ['public_id'])
    op.drop_column('user', 'public_name')
    op.drop_column('user', 'contact')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('contact', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('public_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_unique_constraint('user_public_name_key', 'user', ['public_name'])
    op.drop_column('user', 'public_id')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    op.drop_column('user', 'contact_no')
    # ### end Alembic commands ###
