"""empty message

Revision ID: 845583a15a5a
Revises: 926e3576cf64
Create Date: 2019-03-26 20:29:27.415694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '845583a15a5a'
down_revision = '926e3576cf64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('contact', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'contact')
    # ### end Alembic commands ###
