"""empty message

Revision ID: 8c3dc1d9cb58
Revises: 845583a15a5a
Create Date: 2019-03-26 21:13:19.175222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c3dc1d9cb58'
down_revision = '845583a15a5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('circle',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('contact_num', sa.String(length=20), nullable=True),
    sa.Column('registered_on', sa.DateTime(), nullable=False),
    sa.Column('circle_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('circle_name'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('circle')
    # ### end Alembic commands ###
