"""empty message

Revision ID: be5c77f7f194
Revises: 00a318354350
Create Date: 2019-04-18 08:54:59.797202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be5c77f7f194'
down_revision = '00a318354350'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('breed',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('breed_name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('breed_name')
    )
    op.create_table('pet',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('registered_on', sa.DateTime(), nullable=False),
    sa.Column('pet_name', sa.String(length=255), nullable=True),
    sa.Column('gender', sa.String(length=255), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pet_name')
    )
    op.create_table('breeding_rel_table',
    sa.Column('pet_id', sa.Integer(), nullable=True),
    sa.Column('breed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['breed_id'], ['breed.id'], ),
    sa.ForeignKeyConstraint(['pet_id'], ['pet.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('breeding_rel_table')
    op.drop_table('pet')
    op.drop_table('breed')
    # ### end Alembic commands ###
